# Generated by Django 6.1.1 on 2026-09-30 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('nombre', models.CharField(max_length=100, verbose_name='Descripción del Ítem')),
                ('tipo', models.CharField(choices=[('SUMINISTRO', 'Suministro (Tóner, Drum, etc.)'), ('REPUESTO', 'Repuesto (Fusor, Rodillo, etc.)')], max_length=20, verbose_name='Tipo de Ítem')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible en Stock'), ('ASIGNADO', 'Asignado a Ticket'), ('INSTALADO', 'Instalado / Usado'), ('DEFECTUOSO', 'Defectuoso / Devolución')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='activos/', verbose_name='Fotografía del Ítem')),
            ],
            options={
                'verbose_name': 'Suministro / Repuesto',
                'verbose_name_plural': 'Suministros y Repuestos',
            },
        ),
        migrations.CreateModel(
            name='ModeloImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('tecnologia', models.CharField(default='Láser Monocroma', max_length=50, verbose_name='Tecnología')),
                ('manual_pdf', models.FileField(blank=True, null=True, upload_to='manuales/', verbose_name='Ficha Técnica (PDF)')),
            ],
            options={
                'verbose_name': 'Modelo de Impresora',
                'verbose_name_plural': 'Modelos de Impresoras',
            },
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(max_length=50, unique=True, verbose_name='Número de Ticket / ST')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('tecnico_responsable', models.CharField(default='Técnico La Serena', max_length=100, verbose_name='Técnico Responsable')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Motivo')),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='activos.modeloimpresora', verbose_name='Modelo Impresora')),
                ('item_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='activos.itemactivo', verbose_name='Repuesto / Suministro')),
            ],
            options={
                'verbose_name': 'Solicitud de Servicio (Transacción)',
                'verbose_name_plural': 'Solicitudes de Servicio',
            },
        ),
    ]
