# Generated by Django 6.1.1 on 2026-09-30 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parte', models.CharField(help_text='Código o número de parte del fabricante (ej: CF258A, W1410A)', max_length=100, verbose_name='Número de Parte (P/N)')),
                ('nombre', models.CharField(max_length=100, verbose_name='Descripción del Ítem')),
                ('tipo', models.CharField(choices=[('SUMINISTRO', 'Suministro (Tóner, Drum, etc.)'), ('REPUESTO', 'Repuesto (Fusor, Rodillo, etc.)')], max_length=20, verbose_name='Tipo de Ítem')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible en Stock La Serena'), ('INSTALADO', 'Instalado / Utilizado'), ('DEFECTUOSO', 'Defectuoso / Para Devolución')], default='DISPONIBLE', max_length=20, verbose_name='Estado en Stock')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='activos/', verbose_name='Fotografía del Ítem')),
            ],
            options={
                'verbose_name': 'Ítem de Inventario',
                'verbose_name_plural': 'Inventario de Suministros y Repuestos',
            },
        ),
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='item_asignado',
        ),
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='impresora',
        ),
        migrations.AlterField(
            model_name='modeloimpresora',
            name='manual_pdf',
            field=models.FileField(blank=True, null=True, upload_to='manuales/', verbose_name='Manual / Ficha Técnica (PDF)'),
        ),
        migrations.CreateModel(
            name='RegistroUsoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_santiago', models.CharField(help_text='Número de ticket generado en Santiago para el servicio técnico o suministro.', max_length=50, verbose_name='N° Ticket asignado por Santiago')),
                ('fecha_uso', models.DateField(auto_now_add=True, verbose_name='Fecha de Instalación / Salida')),
                ('tecnico', models.CharField(default='Técnico La Serena', max_length=100, verbose_name='Técnico Ejecutor')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Detalle del Trabajo / Observaciones')),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='activos.modeloimpresora', verbose_name='Modelo de Impresora Atendida')),
                ('item_utilizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='activos.iteminventario', verbose_name='Suministro / Repuesto Utilizado')),
            ],
            options={
                'verbose_name': 'Registro de Consumo / Salida',
                'verbose_name_plural': 'Registros de Consumo / Salidas',
            },
        ),
        migrations.DeleteModel(
            name='ItemActivo',
        ),
        migrations.DeleteModel(
            name='SolicitudServicio',
        ),
    ]
