# Generated by Django 6.1.1 on 2026-10-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_iteminventario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrousoactivo',
            name='impresora',
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='numero_parte',
            field=models.CharField(help_text='Código del fabricante (ej: CF258A, W1410A)', max_length=100, verbose_name='Número de Parte (P/N)'),
        ),
        migrations.AlterField(
            model_name='modeloimpresora',
            name='marca',
            field=models.CharField(default='HP', max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='modeloimpresora',
            name='modelo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='modeloimpresora',
            name='tecnologia',
            field=models.CharField(default='Láser', max_length=50, verbose_name='Tecnología'),
        ),
        migrations.AlterField(
            model_name='registrousoactivo',
            name='item_utilizado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='activos.iteminventario', verbose_name='Suministro / Repuesto Consumido'),
        ),
        migrations.AlterField(
            model_name='registrousoactivo',
            name='ticket_santiago',
            field=models.CharField(help_text='Número de ticket asignado desde Santiago.', max_length=50, verbose_name='N° Ticket Santiago'),
        ),
        migrations.CreateModel(
            name='ImpresoraInstalada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie (S/N)')),
                ('oficina', models.CharField(max_length=150, verbose_name='Oficina / Área')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación Física / Dirección')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instaladas', to='activos.modeloimpresora', verbose_name='Modelo de Impresora')),
            ],
            options={
                'verbose_name': 'Impresora Instalada',
                'verbose_name_plural': 'Impresoras Instaladas',
            },
        ),
        migrations.AddField(
            model_name='registrousoactivo',
            name='impresora_instalada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='activos.impresorainstalada', verbose_name='Impresora Atendida (S/N y Oficina)'),
        ),
    ]
